### ISSUE TITLE
BP Cover Photo Size

### ISSUE THREAD

**Issue by ReneLuecking** [codehaiku/gears#6]
Can you add the possibility to change the size of the Cover Photo? For example you can check, if the constants BCP_MAX_WIDTH, BCP_MAX_HEIGHT, BCP_THUMB_MAX_WIDTH, BCP_THUMB_MAX_HEIGHT are already definded before defining them for yourself. With this option the user has the possibility to set this constants in the wp-config.php

**Comment by codehaiku** [comment]
Thanks for your feedback. Added in 4.1.5 👍
